language: java

jdk:
- oraclejdk8

env:
- GRAILS_VERSION=3.1.1 UPGRADE=upgrade

before_install:
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- gvm install grails $GRAILS_VERSION || true
- chmod 775 ./build.sh

script: ./build.sh
